### ISSUE TITLE
남은 벌금이 (경과된 날 * 500(으로 나옴

### ISSUE THREAD

**Issue by codeisneverodd** [BambooKim/DcomDailyCommitBackend#1]
<img width="841" alt="스크린샷 2022-02-15 오후 4 40 40" src="https://user-images.githubusercontent.com/54318460/154015000-e79b502f-52b3-4a45-9c9d-e444068d3261.png">

src/main/java/.../service/userServiceImpl
line 47
```java
list.get(i).setUnpaidFine(elapsedTimeDay * 500 - list.get(i).getUnpaidFine());
```
에서
```java
list.get(i).setUnpaidFine((elapsedTimeDay- list.get(i).getCommitDayCount()) * 500 - list.get(i).getPaidFine());
```
과 같은 형식이 되야하는건지?

**Comment by BambooKim** [comment]
수정하였습니다.
