### ISSUE TITLE
(긴급) 2022.02.27 19:08 기준, 사용자 등록시 무한로딩 및 500 error 발생

### ISSUE THREAD

**Issue by codeisneverodd** [BambooKim/DcomDailyCommitBackend#3]
등록시도 내용은 다음과 같음

발생 상황
<img width="1786" alt="image" src="https://user-images.githubusercontent.com/54318460/155878202-d6491056-005a-4d4a-a9f5-851831849ec6.png">

**Comment by BambooKim** [comment]
수정하였습니다.

사진에 access code 노출로 사진 삭제하였습니다.
